baseURL = "https://gerkovink.github.io"
title = "Gerko Vink"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[params] # theme parameters
author = "Gerko Vink" # Author's name.
description = "" # Site description.
keywords = "Gerko Vink, Gerko, Vink, Developer, Statistician" # Site keywords.
info = "dark data scientist" # Author's job title or info.
avatarurl = "images/gerko_cartoon.png" # Contain the path of the optionnal avatar in the static folder.
#gravatar = "john.doe@example.com"
dateFormat = "January 2, 2006"
since = 2019
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/gerkovink/gerkovink.github.io/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
footercontent = "occasional Bayesian | incidental frequentist | properly uncertain" # Add footer content
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []


# Social links
[[params.social]]
name = "Github"
weight = 1
url = "https://github.com/gerkovink"
[[params.social]]
name = "LinkedIn"
weight = 2
url = "https://nl.linkedin.com/in/gerko-vink-670b4017"
[[params.social]]
name = "UU"
weight = 3
url = "https://www.uu.nl/staff/GVink/0"
[[params.social]]
name = "Mail me"
weight = 4
url = "mailto:G.Vink@uu.nl"
[[params.social]]
name = "Twitter"
weight = 5
url = "https://twitter.com/OkregK"

# Menu links
[[menu.main]]
name = "About me"
weight = 1
url  = "/abt/"
[[menu.main]]
name = "Courses"
weight = 2
url = "/crs/"
[[menu.main]]
name = "CV"
weight = 2
url = "/cv/Vink.pdf"
[[menu.main]]
name = "Development"
weight = 2
url = "/dvlp/"
[[menu.main]]
name = "Consultation"
weight = 2
url = "/cnslt/"
[[menu.main]]
name = "Research"
weight = 2
url = "/pubs/"
